server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chirp
    username: postgres
    password: 541888
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
app:
  cors-origin: http://localhost:4173